// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw8UJksezkYhlkXzrppLXFIebkwh6XX1s',
    appId: '1:1021246960450:web:7d0ab99ce4d3bc7cba0edb',
    messagingSenderId: '1021246960450',
    projectId: 'medica-37176',
    authDomain: 'medica-37176.firebaseapp.com',
    storageBucket: 'medica-37176.appspot.com',
    measurementId: 'G-QF5R4EC255',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_Geel6y2tvpjRT-1RRzE9bTLFuVhdQLk',
    appId: '1:1021246960450:android:e4ce5907f70bc4b7ba0edb',
    messagingSenderId: '1021246960450',
    projectId: 'medica-37176',
    storageBucket: 'medica-37176.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3P-eBze5bJep8eXOxhvDee-xgVxje1ho',
    appId: '1:1021246960450:ios:880885866467186eba0edb',
    messagingSenderId: '1021246960450',
    projectId: 'medica-37176',
    storageBucket: 'medica-37176.appspot.com',
    iosBundleId: 'com.example.medica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3P-eBze5bJep8eXOxhvDee-xgVxje1ho',
    appId: '1:1021246960450:ios:ccf4af518a13aa9cba0edb',
    messagingSenderId: '1021246960450',
    projectId: 'medica-37176',
    storageBucket: 'medica-37176.appspot.com',
    iosBundleId: 'com.example.medica.RunnerTests',
  );
}
